version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "eslint"
            versions: [">=9.0.0"]
